package main

import "fmt"

/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/

func main() {

	a	:= 1
	b	:= 2
	n	:= 4000000 // Four Million
	sum := 0
	for a < n {
		if a % 2 == 0 {
			sum += a 
		}
		
		c := a
		a = b
		b = c + b
	}
	fmt.Println(sum)	

}
