/*
<p>The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$</p>
<p>Let us list the factors of 28:</p>
\mathbf{28} &amp;\colon 1,2,4,7,14,28
\end{align}
<p>We can see that $28$ is the first triangle number to have over five divisors.</p>
<p>What is the value of the first triangle number to have over five hundred divisors?</p>
*/
package main

import (
	"fmt"
)

func CountFactors(n int) int {
	f := 0
	for i := 1; i*i <= n; i++ {
		if n % i == 0 {
			if n / i == i {
				f++
			} else {	
				f+=2
			}

		}
	}
	return f
}
func main() {

	seq := 1
	for i := 2; CountFactors(seq) <= 500; i++ {
		seq += i
	}
	fmt.Println("Answer", seq)
}
